name = "musiclove"

main = 'src/index.ts'
compatibility_date = '2026-05-07'

routes = [
  { pattern = "theradio.fm/*", zone_name = "theradio.fm" },
  { pattern = "www.theradio.fm/*", zone_name = "theradio.fm" }
]
